image: gitpod/workspace-full

tasks:
  - name: Start Jenkins
    init: |
      docker pull jenkins/jenkins:lts
    command: |
      docker run -p 8080:8080 -p 50000:50000 jenkins/jenkins:lts

ports:
  - port: 8080
    onOpen: open-preview
